name: Testes Jest React Native

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install deps
        run: npm install

      - name: Execute Jest tests
        run: npm run test
